In [ ]:
1+2

3

In [ ]:
a=10
print(a+5)

15


In [ ]:
import this


The Zen of Python, by Tim Peters

Beautiful is better than ugly.
Explicit is better than implicit.
Simple is better than complex.
Complex is better than complicated.
Flat is better than nested.
Sparse is better than dense.
Readability counts.
Special cases aren't special enough to break the rules.
Although practicality beats purity.
Errors should never pass silently.
Unless explicitly silenced.
In the face of ambiguity, refuse the temptation to guess.
There should be one-- and preferably only one --obvious way to do it.
Although that way may not be obvious at first unless you're Dutch.
Now is better than never.
Although never is often better than *right* now.
If the implementation is hard to explain, it's a bad idea.
If the implementation is easy to explain, it may be a good idea.
Namespaces are one honking great idea -- let's do more of those!


In [ ]:
print("Hello World")
print("Welcome")

Hello World
Welcome


In [ ]:
#Single Line & Multi Line Comments
'''
This is a multiline comment
using triple-quoted strings.
It spans multiple lines.
'''
print("HI")

HI


In [ ]:
#Variable Declaration:
a=10
b=20
c=a+b
print(c)
type(c)


30


int

In [ ]:
#integers:
a=10
print(type(a))
print(a*10)
print(a%10)
print(type(a))

<class 'int'>
100
0
<class 'int'>


In [ ]:
#floating:
a=19.5
print(a)
print(type(a))

19.5
<class 'float'>


In [ ]:
#type Casting
a=19.6
print(a)
print(int(a))
b=10
float(b)

19.6
19


10.0

In [ ]:
#boolean
a=True
b=False
print(type(a),type(b))
print(a and b)
print(a or b)
print(a & b)
print(a | b)

<class 'bool'> <class 'bool'>
False
True
False
True


In [ ]:
#Strings
name="Python"
print(name)
print(type(name))

Python
<class 'str'>


In [ ]:
name+" Easy"


'Python Easy'

In [ ]:
#Complex No.
z=1.0-2.8j
print(z)
print(type(z))
print(z.real," ",z.imag)

(1-2.8j)
<class 'complex'>
1.0   -2.8


In [ ]:
#Dynamic Typing & Strong Typing
#Dynamic Typing
a=10
a="HI"
#Strong Typing
print(a+str(1))

HI1


In [ ]:
#String Formating
a=10
print("The Value of a is - ",a)
first_name="Kumar"
Last_name="Mayank"     #{} --> Place Holders
print("My first name is {} and last name is {}".format(first_name,Last_name))
print("My first name is {first} and last name is {last}".format(last=Last_name,first=first_name))

The Value of a is -  10
My first name is Kumar and last name is Mayank
My first name is Kumar and last name is Mayank


In [ ]:
#Input --> always in string format
a=input("Enter no. A ")
b=input("Enter no. B ")
print(a+b)
#TypeCasting
print(int(a)+int(b))

Enter no. A 1
Enter no. B 2
12
3


In [ ]:
 #Control Flow

In [ ]:
#if-else statements:
val=input("Enter the no.: ")
if(int(float(val))%2==0):
  print("The no. is even")
else:
  print("The no. is odd")

#Nested if else condition
age=float(input("Enter the age: "))
if(age<18):
  print("Minor Age")
  if(age<15):
    print("You are in School")
  else:
    print("You are in College")
elif(age>=18 and age<=45):
  print("Mid Age")
elif(age>45 and age<=50):
  print("Senior Mid Age")
else:
  print("Senior Citizen")


Enter the no.: 100.7
The no. is even
Enter the age: 16.6
Minor Age
You are in College


In [ ]:
#Loops Statements:

lst=[1,2,3,4,5,6,7]
sum1=0;
for i in lst:
  print(i**2) #print the square of each element
  sum1=sum1+i
print(sum1)

1
4
9
16
25
36
49


In [ ]:
#find the sum of even and odd numbers:

lst=[1,2,3,4,5,6,7]
even_sum=0
odd_sum=0
for i in lst:
  if(i%2==0):
    even_sum+=i
  else:
    odd_sum+=i
print(even_sum)
print(odd_sum)
print("Even Sum is {}".format(even_sum))
print("Odd Sum is {}".format(odd_sum))

12
16
Even Sum is 12
Odd Sum is 16


In [ ]:
#While Loop

even_sum=0
odd_sum=0
i=0

while(i<=10):
  if(i%2==0):
    even_sum+=i
  else:
    odd_sum+=i
  i+=1
print(even_sum)
print(odd_sum)
print("Even Sum is {}".format(even_sum))
print("Odd Sum is {}".format(odd_sum))


30
25
Even Sum is 30
Odd Sum is 25


In [ ]:
#break
x=1
while(x<7):
  if(x==4):
    break
  print(x)
  x+=1

1
2
3


In [ ]:
#continue
x=0
while(x<7):
  x+=1
  if(x==4):
    continue
  print(x)

1
2
3
5
6
7


In [ ]:
#Logical Operator:--> runs for boolean variables

#and
a=True
b=False
print(a and b)
print(a & b)

#or
print(a or b)
print(a | b)

#not
print(not a)

age=float(input("Enter the age: "))
if(age>=18 and age<=30):
  print("Success Age")

False
False
True
True
False
Enter the age: 21
Success Age


In [ ]:
#Equality Operator:-->comparsion operator

a=10
b=20
print(a==b)
print(a!=b)
print(a is b)
print(a is not b)

age=int(input("Enter the age: "))
if(age==18):
  print("Time to be Successfull")

False
True
False
True
Enter the age: 18
Time to be Successfull


In [ ]:
a="kumar"
print(id(a))#this obj is created in which memory
#if 2 variable is pointing at same object (is)
b="kumar"
print(id(b))
print(a is b) #if 2 variable is pointing at same object (is)
print(a==b) #here we check value wise

140204673553712
140204673553712
True
True


In [ ]:
#is vs ==
#collection walle item ka jo obj create hota h wo diff create hota h eventho the value is same
lst1=[1,2,3]
lst2=[1,2,3]
print(id(lst1))
print(id(lst2))
print(lst1 is lst2)
print(lst1==lst2)

140204673790528
140204673792128
False
True


In [ ]:
marks=float(input("Enter the marks: "))
if(marks>=35):
  print("Pass")
  if(marks>=50 and marks<=75):
    print("First")
  elif(marks>=80):
    print("Distinction")
else:
  print("Fail")

Enter the marks: 89
Pass
Distinction


In [ ]:
print(48//5)
print(48%5)

9
3


In [ ]:
#python number method
print(abs(-55.02))
#ceil/floor is a inbuild method but is present inside 1 module
#floor==gif
import math
print(math.ceil(43.1))
print(math.floor(43.1))
print(math.ceil(-44.1))
print(math.floor(-44.1))
#exp(x)
print(math.exp(1))
print(math.exp(2))
#fabs
print(math.fabs(-10.96))
print(math.fabs(-10))
#log(x)
print(math.log(2.718281828459045))
print(math.log(10))
#log10(x)
print(math.log10(10))
#max()
print(max(1,2,3,4,5.2))
#min()
print(min(1.1,2,3,4,5))
#pow(x,y)--> x^y
print(math.pow(2,3))
#sqrt(x)
print(math.sqrt(16))
#trigo fn
print(math.sin(90))
print(math.sin(math.pi/2))
print(math.cos(0))
print(math.tan(0))
#hypto(a,b)
print(math.hypot(3,4))
#modf()-->split a floating-point number into its fractional and integer parts
print(math.modf(2.5))


55.02
44
43
-44
-45
2.718281828459045
7.38905609893065
10.96
10.0
1.0
2.302585092994046
1.0
5.2
1.1
8.0
4.0
0.8939966636005579
1.0
1.0
0.0
5.0
(0.5, 2.0)


In [ ]:
#List:
'''
A list is a data structure in Python that is a mutable, or changeable,
ordered sequence of elements.
Each element or value that is inside of a list is called an item.
Just as strings are defined as characters between quotes,
lists are defined by having values between square brackets [ ]
'''

In [ ]:
#strings are immutable : if i define the value of string then i cant change its item
str="KUMAR"
print(str)
str="MAYANK"
print(str)
str[0]="K"
print(str)


KUMAR
MAYANK


TypeError: 'str' object does not support item assignment

In [ ]:
##Lists is mutable
lst=[1,2,3,4,"K","Hello"]
print(lst)
print(lst[4])
lst[4]="M"
print(lst[4])
lst=list((1,2,3,4,5))
print(type(lst))
print(lst)
lst=[1,2,3,4,5]
for i in lst:
    print(i**2)
print(len(lst))
print(max(lst))
print(min(lst))

#.append()
lst=[1, 2, 3, 4, 5]
#.append is used to add elements at the end of the list
lst.append("Kumar")
lst.append(["Kumar","Mayank"])
print(lst[:])
print(lst[6][1])
print(lst[2:6])
print(lst)

#.insert()-->insert in a specific order
lst.insert(2,"Hero")
print(lst)
lst.append(["Hello","World"])
print(lst)
lst=[1,2,3]
lst.append([4,5])
print(lst)

#.extend()--->seperately add element at the end of the list
lst=[1,2,3,4,5,6]
lst.extend([8,9])
print(lst)

#Various Operations that we can perform in List
lst=[1,2,3,4,5]
print(sum(lst))
print(lst*5)#here list have been appended 5 times


#Pop() Method: updates list
lst=[1,2,3,4,5]
lst.pop()
print(lst)
lst.pop(2)
print(lst)

#count():Calculates total occurrence of given element of List
lst=[1,1,2,3,4,5]
print(lst.count(1))
#length:Calculates total length of List
print(len(lst))
# index(): Returns the index of first occurrence. Start and End index are not necessary parameters
print(lst.index(1,1,4))
print(lst.index(1))
##Min and Max
print(min(lst))
print(max(lst))

[1, 2, 3, 4, 'K', 'Hello']
K
M
<class 'list'>
[1, 2, 3, 4, 5]
1
4
9
16
25
5
5
1
[1, 2, 3, 4, 5, 'Kumar', ['Kumar', 'Mayank']]
Mayank
[3, 4, 5, 'Kumar']
[1, 2, 3, 4, 5, 'Kumar', ['Kumar', 'Mayank']]
[1, 2, 'Hero', 3, 4, 5, 'Kumar', ['Kumar', 'Mayank']]
[1, 2, 'Hero', 3, 4, 5, 'Kumar', ['Kumar', 'Mayank'], ['Hello', 'World']]
[1, 2, 3, [4, 5]]
[1, 2, 3, 4, 5, 6, 8, 9]
15
[1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5]
[1, 2, 3, 4]
[1, 2, 4]
2
6
1
0
1
5


In [ ]:
#sets:
'''
data type that is iterable, mutable, and has no duplicate elements.
Python's set class represents the mathematical notion of a set.
This is based on a data structure known as a hash table
'''

print(type({})) #dic has key value pair
print(type({1,2,3,4,5,6,"k"})) #sets has indep elements with no duplicacy
print(type(set([1,2,3,4,5,6,"k"])))#set()-->fn accepts only 1 arg so pass the list
print(set([1,2,3,4,5,6,6,"k"]))


## Defining an empy set

set_var= set()
print(set_var)
print(type(set_var))
set_var={1,2,3,4,3}
print(set_var)
set_var={"Avengers","IronMan",'Hitman'}
print(set_var)
print(type(set_var))

## Inbuilt function in sets
set_var.add("Hulk")
print(set_var)
set1={"Avengers","IronMan",'Hitman'}
set2={"Avengers","IronMan",'Hitman','Hulk2'}
print(set2.intersection(set1))
print(set2)
print(set2.intersection_update(set1))
print(set2)

##Difference
set1={"Avengers","IronMan",'Hitman'}
set2={"Avengers","IronMan",'Hitman','Hulk2'}
print(set2.difference(set1))
print(set2)

## Difference update
print(set2.difference_update(set1))
print(set2)
set1={"Avengers","IronMan",'Hitman'}
set2={"Avengers","IronMan",'Hitman','Hulk2'}
#.issuperset
print(set2.issuperset(set1))
print(set1.issuperset(set2))
print(set1.issubset(set2))


<class 'dict'>
<class 'set'>
<class 'set'>
{1, 2, 3, 4, 5, 6, 'k'}
set()
<class 'set'>
{1, 2, 3, 4}
{'Avengers', 'IronMan', 'Hitman'}
<class 'set'>
{'Avengers', 'IronMan', 'Hulk', 'Hitman'}
{'Avengers', 'IronMan', 'Hitman'}
{'Avengers', 'Hitman', 'Hulk2', 'IronMan'}
None
{'Avengers', 'IronMan', 'Hitman'}
{'Hulk2'}
{'Avengers', 'Hitman', 'Hulk2', 'IronMan'}
None
{'Hulk2'}
True
False
True


In [ ]:
#Dictonaries
'''
A dictionary is a collection which is unordered, changeable and indexed.
In Python dictionaries are written with curly brackets, and they have keys and values.
'''


dic={}
print(type(dic))
print(type({}))
print(type({1:"HI"}))
print(type(dict()))
print(dict(name="Kumar",age="21"))#keys should be without quotes
set1={1,2,3,4,5}
print(type(set1))

## Let create a dictionary
my_dict={"Car1": "Audi", "Car2":"BMW","Car3":"Mercidies Benz"}
print(type(my_dict))
print(my_dict)

##Access the item values based on keys
print(my_dict["Car1"])

print(my_dict.keys())
print(my_dict.values())
print(my_dict.items())


# We can even loop throught the dictionaries keys
for x in my_dict: #or my_dict.keys()
    print(x)


# We can even loop throught the dictionaries values
for x in my_dict.values():
    print(x)

# We can also check both keys and values
for x in my_dict.items():
    print(x)

print(my_dict)


## Adding items in Dictionaries
my_dict['car4']='Audi 2.0'
print(my_dict)
my_dict['Car1']='Maruti'
print(my_dict)


#Nested Dictionary
car1_model={'Mercedes':1960}
car2_model={'Audi':1970}
car3_model={'Ambassador':1980}

car_type={'car1':car1_model,'car2':car2_model,'car3':car3_model}
print(car_type)

## Accessing the items in the dictionary
print(car_type['car1'])
print(car_type['car1']['Mercedes'])

<class 'dict'>
<class 'dict'>
<class 'dict'>
<class 'dict'>
{'name': 'Kumar', 'age': '21'}
<class 'set'>
<class 'dict'>
{'Car1': 'Audi', 'Car2': 'BMW', 'Car3': 'Mercidies Benz'}
Audi
dict_keys(['Car1', 'Car2', 'Car3'])
dict_values(['Audi', 'BMW', 'Mercidies Benz'])
dict_items([('Car1', 'Audi'), ('Car2', 'BMW'), ('Car3', 'Mercidies Benz')])
Car1
Car2
Car3
Audi
BMW
Mercidies Benz
('Car1', 'Audi')
('Car2', 'BMW')
('Car3', 'Mercidies Benz')
{'Car1': 'Audi', 'Car2': 'BMW', 'Car3': 'Mercidies Benz'}
{'Car1': 'Audi', 'Car2': 'BMW', 'Car3': 'Mercidies Benz', 'car4': 'Audi 2.0'}
{'Car1': 'Maruti', 'Car2': 'BMW', 'Car3': 'Mercidies Benz', 'car4': 'Audi 2.0'}
{'car1': {'Mercedes': 1960}, 'car2': {'Audi': 1970}, 'car3': {'Ambassador': 1980}}
{'Mercedes': 1960}
1960


In [ ]:
#Tuples -->if we are defining a tuple then we cant change its items.(immutable)
## create an empty Tuples

my_tuple=tuple()
print(type(my_tuple))
my_tuple=()
print(type(my_tuple))
my_tuple=("Kumar","Ankur","John")
my_tuple=('Hello','World')
print(type(my_tuple))
print(my_tuple)
type(my_tuple)
## Inbuilt function
print(my_tuple.count('Hello'))
print(my_tuple.index('Hello'))
print(list(my_tuple))


<class 'tuple'>
<class 'tuple'>
<class 'tuple'>
('Hello', 'World')
1
0
['Hello', 'World']


In [16]:
#Python Numpy Arrays
'''
numpy is a general-purpose array-processing package.
It provides a high-performance multidimensional array object, and tools for working with these arrays.
It is the fundamental package for scientific computing with Python
'''
'''
What is an array?
An array is a data structure that stores values of same data type.
In Python, this is the main difference between arrays and lists.
While python lists can contain values corresponding to different data types, arrays in python can only contain values corresponding to same data type
'''
#import the library
import numpy as np
my_lst=[1,2,3,4,5]
arr=np.array(my_lst)
print(arr)
print(type(arr))
print(arr.shape)

lst1=[1,2,3,4,5]
lst2=[2,3,4,5,6]
lst3=[3,4,5,6,7]
arr1=np.array([lst1,lst2,lst3])
print(arr1)
print(arr1.shape) #(row,coloumn)

print(arr)
#indexing
print(arr[3])
arr[3]=5
print(arr)
print(arr[1:3])
print(arr[-1])
print(arr[:-1])
print(arr[::-2])#last se 2 element ka jump krke print krta h
print(arr[::-3])
print(arr1)
print(arr1[:,1])#select all rows and 1st coloumn
print(arr1[:,1:2])
print(arr1[1:3,1:3])
print(arr1[:,3:])
print(arr1[:,3:].shape)
print(arr1[:,1])
print(arr1[1:,1:3])
print(arr1[1:,3:])


##EDA
print(arr)
print(arr<2)
print(arr[arr<2])
print(arr1)
print(arr1.reshape(5,3))

##mechanism to create an array
print(np.arange(1,20,2).reshape(2,5))#step size=2
print(np.arange(1,20,2).reshape(1,10))
print(np.arange(1,20,2).reshape(2,5,1))
print(arr *arr)
print(arr1 * arr1)
print(np.ones((5,3)))
print(np.zeros((4,5)))
print(np.random.randint(10,50))
print(np.random.randint(10,50,4))
print(np.random.randint(10,50,4).reshape(2,2))
print(np.random.randn(5,6)) #standard normal distribution: mean=0 sd=1
print(np.random.random_sample((4,7)))




[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)
[[1 2 3 4 5]
 [2 3 4 5 6]
 [3 4 5 6 7]]
(3, 5)
[1 2 3 4 5]
4
[1 2 3 5 5]
[2 3]
5
[1 2 3 5]
[5 3 1]
[5 2]
[[1 2 3 4 5]
 [2 3 4 5 6]
 [3 4 5 6 7]]
[2 3 4]
[[2]
 [3]
 [4]]
[[3 4]
 [4 5]]
[[4 5]
 [5 6]
 [6 7]]
(3, 2)
[2 3 4]
[[3 4]
 [4 5]]
[[5 6]
 [6 7]]
[1 2 3 5 5]
[ True False False False False]
[1]
[[1 2 3 4 5]
 [2 3 4 5 6]
 [3 4 5 6 7]]
[[1 2 3]
 [4 5 2]
 [3 4 5]
 [6 3 4]
 [5 6 7]]
[[ 1  3  5  7  9]
 [11 13 15 17 19]]
[[ 1  3  5  7  9 11 13 15 17 19]]
[[[ 1]
  [ 3]
  [ 5]
  [ 7]
  [ 9]]

 [[11]
  [13]
  [15]
  [17]
  [19]]]
[ 1  4  9 25 25]
[[ 1  4  9 16 25]
 [ 4  9 16 25 36]
 [ 9 16 25 36 49]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
42
[11 10 11 33]
[[25 31]
 [21 38]]
[[ 0.54714178 -1.12068113  1.57489122 -0.93993498  1.35158874 -0.1934636 ]
 [-1.67937007 -1.17294061  0.36043788 -1.15489125  1.51985021  0.74538472]
 [-0.6801216   1.91929498  0.05251214

In [ ]:
#Python Pandas Tutorials:Pandas Dataframe,Pandas Series,Pandas Basic Operations

#agar mein pandas library use krke excel ke data ko read krta hu toh wo by default convert hota h ek ds mein i.e., dataframe